### PR TITLE
fix(dapi): set default log level

### PR DESCRIPTION
**Pull request by coolaj86**
Sets the default log level to `"trace"`, same as `.env.example`.

## Issue being fixed or feature implemented

Fails to run when `LOG_LEVEL` is not set. That seems like a non-essential option that shouldn't cause `dapi` to fail to start.

## What was done?

Set a default log level.

## How Has This Been Tested?

`dapi` got past the error I was getting.

## Breaking Changes

N/A

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [x] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by QuantumExplorer** [comment]
The default log level should not be "trace", it should be "debug"

**Comment by coolaj86** [comment]
> The default log level should not be "trace", it should be "debug"

Your wish is my command...

**Comment by QuantumExplorer** [comment]
@shumkov

**Comment by shumkov** [comment]
@coolaj86 please reopen PR and update the branch if this is still actual

**Pull request closed without merging**
