### PR TITLE
fix(drive): query fix for 1 value and no where clause

### PR DESCRIPTION
**Pull request by QuantumExplorer**
## Issue being fixed or feature implemented
We were only returning 1 (now we return up to limit if limit is defined). (Most likely the value was altered to 1 for a test and was forgotten to be reverted). We can also now handle no where clause.

## Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added or updated relevant unit/integration/functional/e2e tests
- [X] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by thephez — APPROVED** [review]
Concept ACK - makes sense I think :smile: Definitely the removing of the hard-coded 1 part :+1:

**Review by PastaPastaPasta — APPROVED** [review]
ultra-light-utACK

**Comment by thephez** [comment]
> ultra-light-utACK

So, did you click on the "Files changed" tab?? :smile:

**Review by shumkov — APPROVED** [review]
Good catch! 👍

**Pull request merged**
