### PR TITLE
feat(drive): added config for grovedb verify on startup

### PR DESCRIPTION
**Pull request by shumkov**
## Issue being fixed or feature implemented

We shouldn't verify grovedb on every start since verification could take a long time on big database

## What was done?

- Added a flag in `DriveConfig` which enables/disables grovedb verification on startup. 
- This flag will be disabled by default.

## How Has This Been Tested?

None

## Breaking Changes

None 

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [x] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by ogabrielides — COMMENTED** [review]
So, if for any reason grovedb is corrupted, the node will stall?

**Comment by shumkov** [comment]
Correct. Drive has a separate CLI command to verify grovedb

**Comment by fominok** [comment]
How to change this parameter in platform, isn't dashmate is supposed to be updated as well?

**Comment by shumkov** [comment]
@fominok yeah, but I don't think we gonna change it in upcoming months. @QuantumExplorer do we? I think we can add it to dashmate later.

**Review by QuantumExplorer — DISMISSED** [review]

**Pull request merged**
