### PR TITLE
build(dapi-grpc): update grpc protoc image

### PR DESCRIPTION
**Pull request by strophy**
## Issue being fixed or feature implemented

We are depending on two unmaintained Docker images to build grpc:
- `strophy/grpc-web-common`
- `strophy/protoc`

We can reduce this to one image, which will make the build faster, simpler and more consistent

## What was done?

I've been working with the upstream project to fix packaging problems and add arm support. This build precedes a functioning release from upstream, when we can stop depending on `strophy` namespaced images

## How Has This Been Tested?

Locally and in CI

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by shumkov** [comment]
It contains changes from #541 for purpose?

**Review by shumkov — CHANGES_REQUESTED** [review]
It contains changes from #541 for purpose?

**Comment by strophy** [comment]
I needed #541 in order to develop and test this, so I think I need to rebase this after #541 is merged so the right commits appear? It wasn't possible to merge it first because GitHub was still rolling out the bugfix, but I wanted to continue work on updating this component. @nmarley maybe something interesting to include in git training?

**Review by shumkov — APPROVED** [review]
Good job! 👍

**Pull request merged**
